const nameOnPass = "NameOfThePassanger";
console.log("Passanger Name: " + nameOnPass);
const nameOnId = "NameOnTheId";
const nameMatch = nameOnPass == nameOnId;
console.log("ID confirmed? " + nameMatch);
const length = 5;
const doesLengthPass = length < 30;
const height = 10;
const doesHeightPass = height < 55;
const isHandBaggageEligible = doesLengthPass && doesHeightPass;
console.log("Is Hand Baggage Eligible? " + isHandBaggageEligible);
const flightDes = "Paris";
const returnFrom = "Venice";
const isRoundTrip = flightDes == returnFrom;
console.log("Round Trip Check? " + isRoundTrip);
const bookings = 10;
const totalCapacity = 30;
const isFlightAvailable = bookings <= totalCapacity;
console.log("Are seats available? " + isFlightAvailable);

document.querySelector("#name").innerHTML = nameOnPass;
document.querySelector("#id").innerHTML = nameMatch;
document.querySelector("#bag").innerHTML = isHandBaggageEligible;
document.querySelector("#des").innerHTML = isRoundTrip;
document.querySelector("#seat").innerHTML = isFlightAvailable;